# Generated by Django 4.2.5 on 2023-10-15 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grievances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to=grievances.models.document_upload_to)),
                ('status', models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved'), ('In-Progress', 'In-Progress'), ('Rejected', 'Rejected')], default='Unsolved', max_length=100)),
                ('report', models.FileField(blank=True, null=True, upload_to=grievances.models.report_upload_to)),
                ('escalatetoHo', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('severity', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
