# Generated by Django 4.2.5 on 2023-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0009_alter_complaint_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(blank=True, default='4', max_length=100, null=True),
        ),
    ]
