# Generated by Django 4.0.3 on 2023-09-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministrativeStaff',
        ),
    ]
