# Generated by Django 4.0.3 on 2023-09-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Faculty'},
        ),
    ]
