# Generated by Django 4.0.3 on 2023-09-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
    ]
