# Generated by Django 4.0.3 on 2023-09-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
