# Generated by Django 4.0.3 on 2023-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Review Committee', 'Review Committee'), ('Assessment Committee', 'Assessment Committee'), ('HO', 'HO')], max_length=50),
        ),
    ]
