# Generated by Django 4.0.3 on 2023-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Review Committee', 'Review Committee'), ('Assessment Committee', 'Assessment Committee'), ('HO', 'HO'), ('Faculty', 'Faculty')], max_length=50),
        ),
    ]
