# Generated by Django 4.0.3 on 2023-09-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='complaints/documents/')),
            ],
        ),
    ]
