# Generated by Django 4.0.3 on 2023-09-19 06:38

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=login.models.report_upload_to),
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
